"""Add original_filename to asset table

Revision ID: 25c59c183ca5
Revises: 47f069c78eaf
Create Date: 2025-11-17 17:45:01.972110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c59c183ca5'
down_revision = '47f069c78eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_page')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=False))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_column('width')
        batch_op.drop_column('height')
        batch_op.drop_column('url')
        batch_op.drop_column('original_name')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_site_subdomain', ['subdomain'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.INTEGER(), nullable=True))
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('file_url')
        batch_op.drop_column('file_path')
        batch_op.drop_column('original_filename')

    op.create_table('_alembic_tmp_page',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('template', sa.VARCHAR(length=50), server_default=sa.text("'default'"), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('html_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_homepage', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('site_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('html_content', sa.TEXT(), nullable=True),
    sa.Column('css_content', sa.TEXT(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
